export const LOGIN = 'APPLICATION/LOGIN';
export const LOGOUT = 'APPLICATION/LOGOUT';
export const SHOW_LOADER = 'APPLICATION/SHOW_LOADER';
export const HIDE_LOADER = 'APPLICATION/HIDE_LOADER';
export const LOADER_PROGRESS = 'APPLICATION/LOADER_PROGRESS';
export const SHOW_ALERT = 'APPLICATION/SHOW_ALERT';
export const HIDE_ALERT = 'APPLICATION/HIDE_ALERT';

export const GET_POSTS = 'POSTS/GET_POSTS';
export const GET_POST = 'POSTS/GET_POST';
export const CLEAR_POST = 'POSTS/CLEAR_POST';
export const REQUEST_POSTS = 'POSTS/REQUEST_POSTS';
export const REQUEST_POST = 'POSTS/REQUEST_POST';