export const LOGIN_REQUEST = 'APP/LOGIN_REQUEST';
export const LOGIN_PROCESSING = 'APP/LOGIN_PROCESSING';
export const LOGIN_SUCCESS = 'APP/LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'APP/LOGIN_FAILURE';
export const LOGOUT = 'APP/LOGOUT';
export const LOADER_SHOW = 'APP/LOADER_SHOW';
export const LOADER_HIDE = 'APP/LOADER_HIDE';
export const LOADER_PROGRESS = 'APP/LOADER_PROGRESS';

export const POSTS_REQUEST = 'POSTS/POSTS_REQUEST';
export const POSTS_SUCCESS = 'POSTS/POSTS_SUCCESS';
export const POSTS_FAILURE = 'POSTS/POSTS_FAILURE';
export const POST_CLEAR = 'POSTS/POST_CLEAR';
export const POST_REQUEST = 'POSTS/POST_REQUEST';
export const POST_SUCCESS = 'POSTS/POST_SUCCESS';
export const POST_FAILURE = 'APP/POST_FAILURE';